name: CraigSkelton
favicon: null
layout_spectrum: 0.99338
typography_spectrum: 0.27738
title: 'Things I like. Craig Skelton that is. '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-2592988-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d42604'
    - '#040604'
    - '#fcfefc'
    - '#fcc604'
    - '#ec7604'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
