name: CraigSkelton
favicon: null
layout_spectrum: 0.9276158113498241
typography_spectrum: 0.047762746224179864
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.3681796642486006
  lightness: 0.2863010203000158
  saturation: 0.10218712082132697
  rhythmicContrast: 0.25528837740421295
purpose: []
